name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем код
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # 3. Устанавливаем Kotlin Compiler
      - name: Install Kotlin Compiler
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin 2.1.0-RC2

      # 4. Сборка проекта
      - name: Build Project
        run: ./gradlew clean build

      # 5. Запуск тестов
      - name: Run Tests
        run: ./gradlew test

      # 6. Сохранение результатов тестов (дополнительно)
      - name: Save test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports/tests/test
